# Experiment 02

# Task 01

## Supervised Classification using Logistic Regression, Linear Discriminant Analysis (LDA), and K-Nearest Neighbors (KNN)

### Student Details

**Name:** Karthik

**Course:** B.Tech AIML

**Experiment:** 02

**Task:** 01

### Objective

To implement and compare three supervised classification algorithms—Logistic Regression, Linear Discriminant Analysis (LDA), and K-Nearest Neighbors (KNN)—using the Iris dataset.

In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split

from sklearn.linear_model import LogisticRegression
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.neighbors import KNeighborsClassifier

from sklearn.metrics import accuracy_score

In [3]:
from google.colab import files

uploaded = files.upload()

Saving iris.csv to iris.csv

In [4]:
iris = pd.read_csv("iris.csv")

iris.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [5]:
X = iris.iloc[:, :-1]

y = iris.iloc[:, -1]

print(X.shape)
print(y.shape)

(150, 4)
(150,)

In [6]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [7]:
lr = LogisticRegression(max_iter=200)

lr.fit(X_train, y_train)

lr_pred = lr.predict(X_test)

print("Accuracy:", accuracy_score(y_test, lr_pred))

Accuracy: 1.0

In [8]:
lda = LinearDiscriminantAnalysis()

lda.fit(X_train, y_train)

lda_pred = lda.predict(X_test)

print("Accuracy:", accuracy_score(y_test, lda_pred))

Accuracy: 1.0

In [9]:
knn = KNeighborsClassifier(n_neighbors=3)

knn.fit(X_train, y_train)

knn_pred = knn.predict(X_test)

print("Accuracy:", accuracy_score(y_test, knn_pred))

Accuracy: 1.0

In [10]:
results = pd.DataFrame({
    "Algorithm":[
        "Logistic Regression",
        "LDA",
        "KNN"
    ],
    "Accuracy":[
        accuracy_score(y_test, lr_pred),
        accuracy_score(y_test, lda_pred),
        accuracy_score(y_test, knn_pred)
    ]
})

results

             Algorithm  Accuracy
0  Logistic Regression       1.0
1                  LDA       1.0
2                  KNN       1.0

In [11]:
# ============================================================
# Experiment 02 - Task 01
# Supervised Classification using Logistic Regression,
# Linear Discriminant Analysis (LDA), and K-Nearest Neighbors (KNN)
# Dataset: Iris
# ============================================================

# Import Required Libraries
import numpy as np
import pandas as pd

from google.colab import files
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

# ------------------------------------------------------------
# Upload Dataset
# ------------------------------------------------------------
print("Upload iris.csv")
uploaded = files.upload()

# ------------------------------------------------------------
# Load Dataset
# ------------------------------------------------------------
iris = pd.read_csv("iris.csv")

print("\n========== First Five Rows ==========")
print(iris.head())

# ------------------------------------------------------------
# Dataset Information
# ------------------------------------------------------------
print("\n========== Dataset Shape ==========")
print(iris.shape)

print("\n========== Dataset Information ==========")
print(iris.info())

print("\n========== Statistical Summary ==========")
print(iris.describe())

# ------------------------------------------------------------
# Prepare Features and Target
# ------------------------------------------------------------
X = iris.iloc[:, :-1]
y = iris.iloc[:, -1]

# ------------------------------------------------------------
# Split Dataset
# ------------------------------------------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("\nTraining Samples :", len(X_train))
print("Testing Samples  :", len(X_test))

# ============================================================
# Logistic Regression
# ============================================================

lr = LogisticRegression(max_iter=200)

lr.fit(X_train, y_train)

lr_prediction = lr.predict(X_test)

lr_accuracy = accuracy_score(y_test, lr_prediction)

print("\n========== Logistic Regression ==========")
print("Accuracy :", lr_accuracy)

# ============================================================
# Linear Discriminant Analysis (LDA)
# ============================================================

lda = LinearDiscriminantAnalysis()

lda.fit(X_train, y_train)

lda_prediction = lda.predict(X_test)

lda_accuracy = accuracy_score(y_test, lda_prediction)

print("\n========== Linear Discriminant Analysis ==========")
print("Accuracy :", lda_accuracy)

# ============================================================
# K-Nearest Neighbors (KNN)
# ============================================================

knn = KNeighborsClassifier(n_neighbors=3)

knn.fit(X_train, y_train)

knn_prediction = knn.predict(X_test)

knn_accuracy = accuracy_score(y_test, knn_prediction)

print("\n========== K-Nearest Neighbors ==========")
print("Accuracy :", knn_accuracy)

# ============================================================
# Model Comparison
# ============================================================

results = pd.DataFrame({
    "Algorithm": [
        "Logistic Regression",
        "Linear Discriminant Analysis",
        "K-Nearest Neighbors"
    ],
    "Accuracy": [
        lr_accuracy,
        lda_accuracy,
        knn_accuracy
    ]
})

print("\n========== Model Comparison ==========")
print(results)

# ============================================================
# Best Model
# ============================================================

best_model = results.loc[results["Accuracy"].idxmax()]

print("\n========== Best Performing Model ==========")
print("Algorithm :", best_model["Algorithm"])
print("Accuracy  :", best_model["Accuracy"])

print("\n========== Task 01 Completed Successfully ==========")

Upload iris.csv

Saving iris.csv to iris (1).csv

========== First Five Rows ==========
   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

========== Dataset Shape ==========
(150, 5)

========== Dataset Information ==========
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB
None

========== Statistical Summary ==========
       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

Training Samples : 120
Testing Samples  : 30

========== Logistic Regression ==========
Accuracy : 1.0

========== Linear Discriminant Analysis ==========
Accuracy : 1.0

========== K-Nearest Neighbors ==========
Accuracy : 1.0

========== Model Comparison ==========
                      Algorithm  Accuracy
0           Logistic Regression       1.0
1  Linear Discriminant Analysis       1.0
2           K-Nearest Neighbors       1.0

========== Best Performing Model ==========
Algorithm : Logistic Regression
Accuracy  : 1.0

========== Task 01 Completed Successfully ==========

# Conclusion

Successfully implemented Logistic Regression, Linear Discriminant Analysis (LDA), and K-Nearest Neighbors (KNN) classifiers using the Iris dataset.

The models were trained and evaluated using accuracy, allowing comparison of their classification performance on the same dataset.