# Experiment 02

# Task 02

## Classification using Naive Bayes and Support Vector Machine (SVM) on the Sonar Dataset

## Student Details

**Name:** Karthik

**Course:** B.Tech AIML

**Experiment:** 02

**Task:** 02

## Objective

To implement and compare Gaussian Naive Bayes and Support Vector Machine (SVM) classifiers using the Sonar dataset.

In [1]:
import numpy as np
import pandas as pd

from google.colab import files

from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC

from sklearn.metrics import accuracy_score

In [2]:
uploaded = files.upload()

Saving sonar.csv to sonar.csv

In [3]:
sonar = pd.read_csv("sonar.csv", header=None)

sonar.head()

,0,1,2,3,4,5,6,7,8,9,...,51,52,53,54,55,56,57,58,59,60
0,0.0200,0.0371,0.0428,0.0207,0.0954,0.0986,0.1539,0.1601,0.3109,0.2111,...,0.0027,0.0065,0.0159,0.0072,0.0167,0.0180,0.0084,0.0090,0.0032,R
1,0.0453,0.0523,0.0843,0.0689,0.1183,0.2583,0.2156,0.3481,0.3337,0.2872,...,0.0084,0.0089,0.0048,0.0094,0.0191,0.0140,0.0049,0.0052,0.0044,R
2,0.0262,0.0582,0.1099,0.1083,0.0974,0.2280,0.2431,0.3771,0.5598,0.6194,...,0.0232,0.0166,0.0095,0.0180,0.0244,0.0316,0.0164,0.0095,0.0078,R
3,0.0100,0.0171,0.0623,0.0205,0.0205,0.0368,0.1098,0.1276,0.0598,0.1264,...,0.0121,0.0036,0.0150,0.0085,0.0073,0.0050,0.0044,0.0040,0.0117,R
4,0.0762,0.0666,0.0481,0.0394,0.0590,0.0649,0.1209,0.2467,0.3564,0.4459,...,0.0031,0.0054,0.0105,0.0110,0.0015,0.0072,0.0048,0.0107,0.0094,R

In [4]:
print("Shape:", sonar.shape)

print("\nFirst Five Rows")
print(sonar.head())

print("\nStatistical Summary")
print(sonar.describe())

Shape: (208, 61)

First Five Rows
       0       1       2       3       4       5       6       7       8   \
0  0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109
1  0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337
2  0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598
3  0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598
4  0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564

       9   ...      51      52      53      54      55      56      57  \
0  0.2111  ...  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180  0.0084
1  0.2872  ...  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140  0.0049
2  0.6194  ...  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316  0.0164
3  0.1264  ...  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050  0.0044
4  0.4459  ...  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072  0.0048

       58      59  60
0  0.0090  0.0032   R
1  0.0052  0.0044   R
2  0.0095  0.0078   R
3  0.0040  0.0117   R
4  0.0107  0.0094   R

[5 rows x 61 columns]

Statistical Summary
               0           1           2           3           4           5   \
count  208.000000  208.000000  208.000000  208.000000  208.000000  208.000000
mean     0.029164    0.038437    0.043832    0.053892    0.075202    0.104570
std      0.022991    0.032960    0.038428    0.046528    0.055552    0.059105
min      0.001500    0.000600    0.001500    0.005800    0.006700    0.010200
25%      0.013350    0.016450    0.018950    0.024375    0.038050    0.067025
50%      0.022800    0.030800    0.034300    0.044050    0.062500    0.092150
75%      0.035550    0.047950    0.057950    0.064500    0.100275    0.134125
max      0.137100    0.233900    0.305900    0.426400    0.401000    0.382300

               6           7           8           9   ...          50  \
count  208.000000  208.000000  208.000000  208.000000  ...  208.000000
mean     0.121747    0.134799    0.178003    0.208259  ...    0.016069
std      0.061788    0.085152    0.118387    0.134416  ...    0.012008
min      0.003300    0.005500    0.007500    0.011300  ...    0.000000
25%      0.080900    0.080425    0.097025    0.111275  ...    0.008425
50%      0.106950    0.112100    0.152250    0.182400  ...    0.013900
75%      0.154000    0.169600    0.233425    0.268700  ...    0.020825
max      0.372900    0.459000    0.682800    0.710600  ...    0.100400

               51          52          53          54          55          56  \
count  208.000000  208.000000  208.000000  208.000000  208.000000  208.000000
mean     0.013420    0.010709    0.010941    0.009290    0.008222    0.007820
std      0.009634    0.007060    0.007301    0.007088    0.005736    0.005785
min      0.000800    0.000500    0.001000    0.000600    0.000400    0.000300
25%      0.007275    0.005075    0.005375    0.004150    0.004400    0.003700
50%      0.011400    0.009550    0.009300    0.007500    0.006850    0.005950
75%      0.016725    0.014900    0.014500    0.012100    0.010575    0.010425
max      0.070900    0.039000    0.035200    0.044700    0.039400    0.035500

               57          58          59
count  208.000000  208.000000  208.000000
mean     0.007949    0.007941    0.006507
std      0.006470    0.006181    0.005031
min      0.000300    0.000100    0.000600
25%      0.003600    0.003675    0.003100
50%      0.005800    0.006400    0.005300
75%      0.010350    0.010325    0.008525
max      0.044000    0.036400    0.043900

[8 rows x 60 columns]

In [5]:
X = sonar.iloc[:, :-1]

y = sonar.iloc[:, -1]

In [6]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [7]:
nb = GaussianNB()

nb.fit(X_train, y_train)

nb_pred = nb.predict(X_test)

nb_accuracy = accuracy_score(y_test, nb_pred)

print("Naive Bayes Accuracy:", nb_accuracy)

Naive Bayes Accuracy: 0.7380952380952381

In [8]:
svm = SVC()

svm.fit(X_train, y_train)

svm_pred = svm.predict(X_test)

svm_accuracy = accuracy_score(y_test, svm_pred)

print("SVM Accuracy:", svm_accuracy)

SVM Accuracy: 0.8333333333333334

In [9]:
results = pd.DataFrame({
    "Algorithm": [
        "Gaussian Naive Bayes",
        "Support Vector Machine"
    ],
    "Accuracy": [
        nb_accuracy,
        svm_accuracy
    ]
})

results

                Algorithm  Accuracy
0    Gaussian Naive Bayes  0.738095
1  Support Vector Machine  0.833333

In [10]:
# ==========================================================
# Experiment 02 - Task 02
# Naive Bayes and Support Vector Machine on Sonar Dataset
# ==========================================================

import numpy as np
import pandas as pd

from google.colab import files

from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

# Upload Dataset
print("Upload sonar.csv")
uploaded = files.upload()

# Load Dataset
sonar = pd.read_csv("sonar.csv", header=None)

print("\nFirst Five Rows")
print(sonar.head())

print("\nDataset Shape")
print(sonar.shape)

print("\nStatistical Summary")
print(sonar.describe())

# Features and Target
X = sonar.iloc[:, :-1]
y = sonar.iloc[:, -1]

# Split Dataset
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# Gaussian Naive Bayes
nb = GaussianNB()
nb.fit(X_train, y_train)
nb_pred = nb.predict(X_test)
nb_accuracy = accuracy_score(y_test, nb_pred)

print("\nNaive Bayes Accuracy:", nb_accuracy)

# Support Vector Machine
svm = SVC()
svm.fit(X_train, y_train)
svm_pred = svm.predict(X_test)
svm_accuracy = accuracy_score(y_test, svm_pred)

print("SVM Accuracy:", svm_accuracy)

# Comparison
results = pd.DataFrame({
    "Algorithm": [
        "Gaussian Naive Bayes",
        "Support Vector Machine"
    ],
    "Accuracy": [
        nb_accuracy,
        svm_accuracy
    ]
})

print("\nModel Comparison")
print(results)

best = results.loc[results["Accuracy"].idxmax()]

print("\nBest Model")
print(best)

print("\nTask 02 Completed Successfully")

Upload sonar.csv

Saving sonar.csv to sonar (1).csv

First Five Rows
       0       1       2       3       4       5       6       7       8   \
0  0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109
1  0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337
2  0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598
3  0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598
4  0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564

       9   ...      51      52      53      54      55      56      57  \
0  0.2111  ...  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180  0.0084
1  0.2872  ...  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140  0.0049
2  0.6194  ...  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316  0.0164
3  0.1264  ...  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050  0.0044
4  0.4459  ...  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072  0.0048

       58      59  60
0  0.0090  0.0032   R
1  0.0052  0.0044   R
2  0.0095  0.0078   R
3  0.0040  0.0117   R
4  0.0107  0.0094   R

[5 rows x 61 columns]

Dataset Shape
(208, 61)

Statistical Summary
               0           1           2           3           4           5   \
count  208.000000  208.000000  208.000000  208.000000  208.000000  208.000000
mean     0.029164    0.038437    0.043832    0.053892    0.075202    0.104570
std      0.022991    0.032960    0.038428    0.046528    0.055552    0.059105
min      0.001500    0.000600    0.001500    0.005800    0.006700    0.010200
25%      0.013350    0.016450    0.018950    0.024375    0.038050    0.067025
50%      0.022800    0.030800    0.034300    0.044050    0.062500    0.092150
75%      0.035550    0.047950    0.057950    0.064500    0.100275    0.134125
max      0.137100    0.233900    0.305900    0.426400    0.401000    0.382300

               6           7           8           9   ...          50  \
count  208.000000  208.000000  208.000000  208.000000  ...  208.000000
mean     0.121747    0.134799    0.178003    0.208259  ...    0.016069
std      0.061788    0.085152    0.118387    0.134416  ...    0.012008
min      0.003300    0.005500    0.007500    0.011300  ...    0.000000
25%      0.080900    0.080425    0.097025    0.111275  ...    0.008425
50%      0.106950    0.112100    0.152250    0.182400  ...    0.013900
75%      0.154000    0.169600    0.233425    0.268700  ...    0.020825
max      0.372900    0.459000    0.682800    0.710600  ...    0.100400

               51          52          53          54          55          56  \
count  208.000000  208.000000  208.000000  208.000000  208.000000  208.000000
mean     0.013420    0.010709    0.010941    0.009290    0.008222    0.007820
std      0.009634    0.007060    0.007301    0.007088    0.005736    0.005785
min      0.000800    0.000500    0.001000    0.000600    0.000400    0.000300
25%      0.007275    0.005075    0.005375    0.004150    0.004400    0.003700
50%      0.011400    0.009550    0.009300    0.007500    0.006850    0.005950
75%      0.016725    0.014900    0.014500    0.012100    0.010575    0.010425
max      0.070900    0.039000    0.035200    0.044700    0.039400    0.035500

               57          58          59
count  208.000000  208.000000  208.000000
mean     0.007949    0.007941    0.006507
std      0.006470    0.006181    0.005031
min      0.000300    0.000100    0.000600
25%      0.003600    0.003675    0.003100
50%      0.005800    0.006400    0.005300
75%      0.010350    0.010325    0.008525
max      0.044000    0.036400    0.043900

[8 rows x 60 columns]

Naive Bayes Accuracy: 0.7380952380952381
SVM Accuracy: 0.8333333333333334

Model Comparison
                Algorithm  Accuracy
0    Gaussian Naive Bayes  0.738095
1  Support Vector Machine  0.833333

Best Model
Algorithm    Support Vector Machine
Accuracy                   0.833333
Name: 1, dtype: object

Task 02 Completed Successfully

# Conclusion

Successfully implemented Gaussian Naive Bayes and Support Vector Machine (SVM) classifiers using the Sonar dataset.

The models were trained and evaluated using accuracy, allowing comparison of their performance on the same classification problem.